elm=document.getElementById("dd");
elm.addEventListener("mousedown",function(e){
    sx=e.layerX;
    sy=e.layerY;
    p=document.getElementsByTagName("path")[0];
    elm.addEventListener("mousemove",function(e){
        kx=e.layerX;
        ky=e.layerY;
        dx=kx-sx;
        dy=ky-sy;
        console.log(dx,dy);
        pth=p.getAttribute("d");
        //p.setAttribute("d",scale(pth,dx,dy)); 
        sx=kx;
        sy=ky;
    })
})